plugins {
    id 'com.android.application'
}

android {
    namespace 'com.clowneon1.streampe'
    compileSdk 36

    defaultConfig {
        applicationId "com.clowneon1.streampe"
        minSdk 30
        targetSdk 36
        versionCode 2
        versionName "2.0.0"
    }

    signingConfigs {
        release {
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    constraints {
        implementation("org.apache.httpcomponents:httpclient:4.5.14")
    }
}
